### ISSUE TITLE
paperclip clears association

### ISSUE THREAD

**Issue by sashazykov** [thoughtbot/paperclip#1126]
I have a problem with creating associations with paperclip.

Controller:

``` ruby
@ad = Ad.find params[:ad_id]
@banner = @ad.banners.new(params[:banner])
@banner.save
```

Models:

``` ruby
class Ad < ActiveRecord::Base
  has_many :banners, :dependent => :destroy
end

class Banner < ActiveRecord::Base

  ALLOWED_TYPES = %r{^(image|(x-)?application)/(gif|jpeg|jpg|pjpeg|png|x-png)$}

  belongs_to :ad
  attr_accessible :image, :height, :width

  Paperclip.interpolates :banner_path do |attachment, style|
    "ads/#{attachment.instance.ad_id}/banners/#{attachment.instance.width}x#{attachment.instance.height}"
  end

  has_attached_file :image, :url  => "/system/:banner_path",
                            :path => ":rails_root/public/system/:banner_path"

  validates_attachment :image,  :presence => true,
                                :content_type => { :content_type => ALLOWED_TYPES },
                                :size => { :in => 0..300.kilobytes }

  before_validation :extract_dimensions, :on => :create

  # validate do
  #   errors.add('ad_id', 'cannot be changed') if self.ad_id_changed? && !self.ad_id_was.nil?
  # end

  validate do
    if self.ad.banners.where(:width => self.width, :height => self.height).count > 0
      errors.add(:base, "size should be uniq")
    end
  end

  def extract_dimensions
    return unless image?
    tempfile = image.queued_for_write[:original]
    unless tempfile.nil?
      geometry = Paperclip::Geometry.from_file(tempfile)
      self.width = geometry.width.to_i
      self.height = geometry.height.to_i
    end
  end

end
```

Params:

```
  Parameters: {"banner"=>{"image"=>#<ActionDispatch::Http::UploadedFile:0x007ffabe3f93a8 @original_filename="cover.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"banner[image]\"; filename=\"cover.jpg\"\r\nContent-Type: image/jpeg\r\n", @tempfile=#<File:/var/folders/v3/jpxqxljd5gq33qp8lntmnzd00000gn/T/RackMultipart20130107-42769-16b7b8>>}, "ad_id"=>"38"}
```

This code works fine with paperclip 3.3.1, but it fails with the last stable version or HEAD. The error happens because ad_id is nil during validations.

```
NoMethodError (undefined method `banners' for nil:NilClass):
  app/models/banner.rb:28:in `block in <class:Banner>'
  app/controllers/banners_controller.rb:20:in `create'
```

It fails on `self.ad.banners.where(:width => self.width, :height => self.height).count > 0` because `ad_id` is `nil`.

If I remove `params[:banner]` from controller, `ad_id` is not `nil` during validations, thought there is no `ad_id` in `params[:banners]`.

``` ruby
@banner = @ad.banners.new # code without params works, but I need to upload file
```
