### ISSUE TITLE
undefined method `split' for :http:Symbol (3.0.4)

### ISSUE THREAD

**Issue by johnpray** [thoughtbot/paperclip#883]
I'm using Paperclip with S3 on Heroku and locally for development. Usually works wonderfully.

After upgrading my gem from 3.0.3 to 3.0.4 (which happened automatically since I specified `'~> 3.0.2'`), my app started crashing on every page (since just about every page uses paperclip) with this error in the logs locally and on Heroku:

`ActionView::Template::Error (undefined method `split' for :http:Symbol)`

Changing my Gemfile to use 3.0.3 explicity fixed the problem.

I don't think I'm doing anything odd, but if I am, it wasn't a problem until 3.0.4.
