### ISSUE TITLE
NoMethodError (undefined method `has_attached_file' for #<Class:0xb666b884>):  rails 3.2

### ISSUE THREAD

**Issue by urjitrajgor** [thoughtbot/paperclip#705]
I have error in model file my model is looking like

class User < ActiveRecord::Base
  has_attached_file :avatar,
   :style => { :medium => "300x300>", :thumb => "100x100>" }

end

NoMethodError (undefined method `has_attached_file' for #Class:0xb666b884):

so is it working in rails 3.2?

**Comment by nickdb93** [comment]
I'm getting the same error, and restarting does nothing for me. I hope this isn't a stupid mistake, but Google isn't really helping me.

    class AppsController < ApplicationController
      before_action :set_app, only: [:show, :edit, :update, :destroy]
      before_filter :require_permission, except: [:new, :create, :index]
      before_filter :authenticate_user!, except: :index
      has_attached_file :appimage, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
      validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

      gem "paperclip", "~> 4.2"

**Comment by ldco2016** [comment]
Is anyone keeping up on this? I am getting the same problem and my model looks like this:

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :username
         
  has_many :articles
  has_many :comments
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" } #, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

Any help from anyone would be greatly appreciated.

**Comment by dhairyagabha** [comment]
I have ran into the same issue, have done quite a bit of googling but nothing conclusive. According to my situation, I started with carrierwave but then chose not to proceed with it and moved to paperclip. I am building an engine and have an assets table and a join table article assets and here is my migration for adding paperclip to assets table:

```
class AddAttributesToAsset < ActiveRecord::Migration[5.0]
  def change
    add_column :webmanager_assets, :asset_file_name, :string
    add_column :webmanager_assets, :asset_file_size, :integer
    add_column :webmanager_assets, :asset_content_type, :string
  end
end
```
and my model looks something like this:

```
module Webmanager
  class Asset < ApplicationRecord
    has_many :articles_assets
    has_many :articles, through: :articles_assets
    has_attached_file :asset
  end
end
```
I have a rails 5.0.2 rails engine and ruby 2.3.0

I get the following error:

```
NoMethodError in Webmanager::AssetsController#index
undefined method `has_attached_file' for #<Class:0x007fe248d192a0>

Extracted source (around line #21):
19      send(name, *arguments, &block)
20    else
21      super
22    end
23   end
24
Rails.root: /Users/dhairya/sites/radhamadhav
```

**Comment by davedash** [comment]
I am running into this issue while upgrading my app from rails 4.2 to rails 5.0.

To get past this error, for the affected class I followed the instructions here:

https://github.com/thoughtbot/paperclip#installation

Effectively, I added `include Paperclip::Glue` to my model.

I know in my specific case there's probably some assumptions we made with models and auto-loading in our app, that no longer are true in 5.0 so that's why this helped in our case.

Good luck.
