### ISSUE TITLE
Dynamic styles: undefined method `instance' for :original:Symbol

### ISSUE THREAD

**Issue by kotor-le-chat** [thoughtbot/paperclip#1150]
I have the following paperclip attachment with custom dynamic styles in one of my model:

``` ruby
has_attached_file :image, :styles => lambda { |attachment|
    st = attachment.instance.screen_type
    return {
      :medium => "#{st.medium_width}x#{st.medium_height}",
      :small => "#{st.small_width}x#{st.small_height}"
    }
  }
```

This used to work fine with 3.3.0, but with 3.4.0, creating new objects makes `attachment.instance` raise the following error:

undefined method `instance' for :original:Symbol
"/app/app/models/step.rb:11:in`block in class:Step'", "/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.4.0/lib/paperclip/storage/s3.rb:310:in `[]'", "/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.4.0/lib/paperclip/storage/s3.rb:310:in`block in flush_writes'", "/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.4.0/lib/paperclip/storage/s3.rb:297:in `each'", "/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.4.0/lib/paperclip/storage/s3.rb:297:in`flush_writes'", "/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.4.0/lib/paperclip/attachment.rb:212:in `save'", "/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.4.0/lib/paperclip/instance_methods.rb:17:in`block in save_attached_files'", "/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.4.0/lib/paperclip/instance_methods.rb:10:in `block in each_attachment'", "/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.4.0/lib/paperclip/instance_methods.rb:9:in`each'", "/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.4.0/lib/paperclip/instance_methods.rb:9:in `each_attachment'", "/app/vendor/bundle/ruby/1.9.1/gems/paperclip-3.4.0/lib/paperclip/instance_methods.rb:16:in`save_attached_files'"

**Comment by iashanmugavel** [comment]
Still I am getting paperclip 4.2.1.

**Comment by nexhealth** [comment]
:+1:
