### ISSUE TITLE
validation errors after upgrade to 4.3.0 from 3.5.4 for unusual file types with validates_attachment_file_name

### ISSUE THREAD

**Issue by bwlang** [thoughtbot/paperclip#1942]
Tests work for me, but I have received multiple reports from users of problems uploading files. Attempts to reproduce with user files fail...

I did capture a backtrace for one class of error.

With some (valid) user input I see this error (see below for backtrace): 	

```
NoMethodError: undefined method `split' for 0:Fixnum
this referred to the following attachment
validates_attachment_file_name :pcrd, :matches => /pcrd\Z/i
```

I also have reports of "Data has contents that are not what they are reported to be". when I'm only checking for file extensions.

I don't think the file_type validation stuff is fully baked for non canonical file types.
For now I'm just disabling all the validates_attachment_file_name  and using
do_not_validate_attachment_file_type...

<pre>
paperclip-4.3.0/lib/paperclip/media_type_spoof_detector.rb:54→ supplied_media_type
paperclip-4.3.0/lib/paperclip/media_type_spoof_detector.rb:37→ supplied_type_mismatch?
paperclip-4.3.0/lib/paperclip/media_type_spoof_detector.rb:33→ media_type_mismatch?
paperclip-4.3.0/lib/paperclip/media_type_spoof_detector.rb:14→ spoofed?
paperclip-4.3.0/lib/paperclip/validators/media_type_spoof_detection_validator.rb:8→ validate_each
activemodel-4.2.1/lib/active_model/validator.rb:151→ block in validate
activemodel-4.2.1/lib/active_model/validator.rb:148→ each
activemodel-4.2.1/lib/active_model/validator.rb:148→ validate
paperclip-4.3.0/lib/paperclip/validators.rb:68→ block in create_validating_before_filter
activesupport-4.2.1/lib/active_support/callbacks.rb:446→ instance_exec
activesupport-4.2.1/lib/active_support/callbacks.rb:446→ block in make_lambda
activesupport-4.2.1/lib/active_support/callbacks.rb:145→ call
activesupport-4.2.1/lib/active_support/callbacks.rb:145→ block in halting_and_conditional
activesupport-4.2.1/lib/active_support/callbacks.rb:504→ call
activesupport-4.2.1/lib/active_support/callbacks.rb:504→ block in call
activesupport-4.2.1/lib/active_support/callbacks.rb:504→ each
activesupport-4.2.1/lib/active_support/callbacks.rb:504→ call
activesupport-4.2.1/lib/active_support/callbacks.rb:92→ _run_callbacks
activesupport-4.2.1/lib/active_support/callbacks.rb:776→ _run_pcrd_post_process_callbacks
activesupport-4.2.1/lib/active_support/callbacks.rb:81→ run_callbacks
paperclip-4.3.0/lib/paperclip/callbacks.rb:36→ run_paperclip_callbacks
paperclip-4.3.0/lib/paperclip/attachment.rb:503→ block in post_process
activesupport-4.2.1/lib/active_support/callbacks.rb:88→ call
activesupport-4.2.1/lib/active_support/callbacks.rb:88→ _run_callbacks
activesupport-4.2.1/lib/active_support/callbacks.rb:776→ _run_post_process_callbacks
activesupport-4.2.1/lib/active_support/callbacks.rb:81→ run_callbacks
paperclip-4.3.0/lib/paperclip/callbacks.rb:36→ run_paperclip_callbacks
paperclip-4.3.0/lib/paperclip/attachment.rb:502→ post_process
paperclip-4.3.0/lib/paperclip/attachment.rb:458→ post_process_file
paperclip-4.3.0/lib/paperclip/attachment.rb:108→ assign
paperclip-4.3.0/lib/paperclip/has_attached_file.rb:66→ block in define_setter
activerecord-4.2.1/lib/active_record/attribute_assignment.rb:54→ public_send
activerecord-4.2.1/lib/active_record/attribute_assignment.rb:54→ _assign_attribute
activerecord-4.2.1/lib/active_record/attribute_assignment.rb:41→ block in assign_attributes
actionpack-4.2.1/lib/action_controller/metal/strong_parameters.rb:183→ each_pair
actionpack-4.2.1/lib/action_controller/metal/strong_parameters.rb:183→ each_pair
activerecord-4.2.1/lib/active_record/attribute_assignment.rb:35→ assign_attributes
activerecord-4.2.1/lib/active_record/persistence.rb:250→ block in update
activerecord-4.2.1/lib/active_record/transactions.rb:347→ block in with_transaction_returning_status
activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213→ block in transaction
activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188→ within_new_transaction
activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213→ transaction
activerecord-4.2.1/lib/active_record/transactions.rb:220→ transaction
activerecord-4.2.1/lib/active_record/transactions.rb:344→ with_transaction_returning_status
activerecord-4.2.1/lib/active_record/persistence.rb:249→ update
app/controllers/bio_rad_qpcr_experiments_controller.rb:65→ block in update
actionpack-4.2.1/lib/action_controller/metal/mime_responds.rb:210→ respond_to
app/controllers/bio_rad_qpcr_experiments_controller.rb:64→ update
actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4→ send_action
actionpack-4.2.1/lib/abstract_controller/base.rb:198→ process_action
actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10→ process_action
actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20→ block in process_action
activesupport-4.2.1/lib/active_support/callbacks.rb:117→ call
activesupport-4.2.1/lib/active_support/callbacks.rb:117→ call
activesupport-4.2.1/lib/active_support/callbacks.rb:555→ block (2 levels) in compile
activesupport-4.2.1/lib/active_support/callbacks.rb:505→ call
activesupport-4.2.1/lib/active_support/callbacks.rb:505→ call
activesupport-4.2.1/lib/active_support/callbacks.rb:92→ _run_callbacks
activesupport-4.2.1/lib/active_support/callbacks.rb:776→ _run_process_action_callbacks
activesupport-4.2.1/lib/active_support/callbacks.rb:81→ run_callbacks
actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19→ process_action
actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29→ process_action
actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32→ block in process_action
activesupport-4.2.1/lib/active_support/notifications.rb:164→ block in instrument
activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20→ instrument
activesupport-4.2.1/lib/active_support/notifications.rb:164→ instrument
actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30→ process_action
actionpack-4.2.1/lib/action_controller/metal/params_wrapper.rb:250→ process_action
activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:18→ process_action
actionpack-4.2.1/lib/abstract_controller/base.rb:137→ process
actionview-4.2.1/lib/action_view/rendering.rb:30→ process
actionpack-4.2.1/lib/action_controller/metal.rb:196→ dispatch
actionpack-4.2.1/lib/action_controller/metal/rack_delegation.rb:13→ dispatch
actionpack-4.2.1/lib/action_controller/metal.rb:237→ block in action
actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74→ call
actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74→ dispatch
actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:43→ serve
actionpack-4.2.1/lib/action_dispatch/journey/router.rb:43→ block in serve
actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30→ each
actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30→ serve
actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:819→ call
rack-1.6.0/lib/rack/etag.rb:24→ call
rack-1.6.0/lib/rack/conditionalget.rb:38→ call
rack-1.6.0/lib/rack/head.rb:13→ call
actionpack-4.2.1/lib/action_dispatch/middleware/params_parser.rb:27→ call
actionpack-4.2.1/lib/action_dispatch/middleware/flash.rb:260→ call
rack-1.6.0/lib/rack/session/abstract/id.rb:225→ context
rack-1.6.0/lib/rack/session/abstract/id.rb:220→ call
actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:560→ call
activerecord-4.2.1/lib/active_record/query_cache.rb:36→ call
activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:649→ call
actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:29→ block in call
activesupport-4.2.1/lib/active_support/callbacks.rb:88→ call
activesupport-4.2.1/lib/active_support/callbacks.rb:88→ _run_callbacks
activesupport-4.2.1/lib/active_support/callbacks.rb:776→ _run_call_callbacks
activesupport-4.2.1/lib/active_support/callbacks.rb:81→ run_callbacks
actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:27→ call
actionpack-4.2.1/lib/action_dispatch/middleware/remote_ip.rb:78→ call
actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:17→ call
actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30→ call
railties-4.2.1/lib/rails/rack/logger.rb:38→ call_app
railties-4.2.1/lib/rails/rack/logger.rb:20→ block in call
activesupport-4.2.1/lib/active_support/tagged_logging.rb:68→ block in tagged
activesupport-4.2.1/lib/active_support/tagged_logging.rb:26→ tagged
activesupport-4.2.1/lib/active_support/tagged_logging.rb:68→ tagged
railties-4.2.1/lib/rails/rack/logger.rb:20→ call
request_store-1.1.0/lib/request_store/middleware.rb:8→ call
actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21→ call
rack-1.6.0/lib/rack/methodoverride.rb:22→ call
rack-1.6.0/lib/rack/runtime.rb:18→ call
activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28→ call
rack-1.6.0/lib/rack/sendfile.rb:113→ call
actionpack-4.2.1/lib/action_dispatch/middleware/ssl.rb:24→ call
railties-4.2.1/lib/rails/engine.rb:518→ call
railties-4.2.1/lib/rails/application.rb:164→ call
/home/deploy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/passenger-4.0.53/lib/phusion_passenger/rack/thread_handler_extension.rb:74→ process_request
/home/deploy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/passenger-4.0.53/lib/phusion_passenger/request_handler/thread_handler.rb:141→ accept_and_process_next_request
/home/deploy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/passenger-4.0.53/lib/phusion_passenger/request_handler/thread_handler.rb:109→ main_loop
/home/deploy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/passenger-4.0.53/lib/phusion_passenger/request_handler.rb:455→ block (3 levels) in start_threads
</pre>

**Comment by tute** [comment]
@jyurek or @bwlang do you think we need this patch in paperclip?

**Comment by tute** [comment]
Closing, as no one has reported this issue before, but will keep it in mind in case I see it. Thank you for informing us.
