### ISSUE TITLE
undefined method `exitstatus' for nil:NilClass

### ISSUE THREAD

**Issue by jonmagic** [thoughtbot/paperclip#2]
Paperclip 2.2.8 works fine with my app on linux (Ubuntu 8.0.4) but when I try to run my app on Windows (that has ImageMagick 6.5.2 Q16) Paperclip tanks. Initially it was giving me the error this guy was getting, http://bit.ly/14PPyS, but after applying his fix I started getting a new error.

undefined method `exitstatus' for nil:NilClass

I ran "rake test" inside the gem dir on linux and windows, and on windows it had 3 errors and 1 failure.

1) Error:
A multipage PDF being thumbnailed at 100x100 with cropping should create the thumbnail when sent #make. Paperclip::NotIdentifiedByImageMagickError: ./test/fixtures/twopage.pdf is not recognized by the `identify' command.

2) Error:
A multipage PDF being thumbnailed at 100x100 with cropping should report its current and target geometries. Paperclip::NotIdentifiedByImageMagickError: ./test/fixtures/twopage.pdf is not recognized by the `identify' command.

3) Error:
A multipage PDF being thumbnailed at 100x100 with cropping should report its correct format. Paperclip::NotIdentifiedByImageMagickError: ./test/fixtures/twopage.pdf is not recognized by the `identify' command.

4) Failure:
A multipage PDF should start with two pages with dimensions 612x792.
("612x792612x792") expected but was
("")

Tests pass fine on osx and ubuntu.
