### ISSUE TITLE
Rake tasks doesn't working with Rails 2.3.3

### ISSUE THREAD

**Issue by sobrinho** [thoughtbot/paperclip#83]
Hi,

I tried to to run the rake task to reprocess the images and this fail. See:

<pre>rake paperclip:refresh:thumbnails CLASS=Image --trace
(in /var/rails/bhdasgerais)
** Invoke paperclip:refresh:thumbnails (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute paperclip:refresh:thumbnails
rake aborted!
undefined method `file?' for #<Paperclip::Attachment:0x7fd6e850c9d8>
/var/rails/bhdasgerais/vendor/plugins/paperclip/lib/paperclip.rb:236:in `data?'
/var/rails/bhdasgerais/vendor/plugins/paperclip/tasks/paperclip_tasks.rake:25:in `send'
/var/rails/bhdasgerais/vendor/plugins/paperclip/tasks/paperclip_tasks.rake:25:in `for_all_attachments'
/var/rails/bhdasgerais/vendor/plugins/paperclip/tasks/paperclip_tasks.rake:24:in `each'
/var/rails/bhdasgerais/vendor/plugins/paperclip/tasks/paperclip_tasks.rake:24:in `for_all_attachments'
/var/rails/bhdasgerais/vendor/plugins/paperclip/tasks/paperclip_tasks.rake:22:in `each'
/var/rails/bhdasgerais/vendor/plugins/paperclip/tasks/paperclip_tasks.rake:22:in `for_all_attachments'
/var/rails/bhdasgerais/vendor/plugins/paperclip/tasks/paperclip_tasks.rake:44
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/var/lib/gems/1.8/gems/rake-0.8.7/bin/rake:31
/var/lib/gems/1.8/bin/rake:19:in `load'
/var/lib/gems/1.8/bin/rake:19</pre>

I think this is a Papercilp issue
