### ISSUE TITLE
validates_attachment_content_type fails when upgrading from 2.3.1.1 to 2.3.4

### ISSUE THREAD

**Issue by jimmysoho** [thoughtbot/paperclip#331]
Using rails 2.3.9 and paperclip 2.3.1.1 I have this in a dozen models:

  validates_attachment_content_type 'avatar', :content_type => VALID_CONTENT_TYPES

All these models don't have an avatar_content_type column.

When upgrading to paperclip 2.3.4 this fails, e.g.:

```
undefined method `avatar_content_type' for #<Account:0x1060b1678>
```

whenever you try to save an object (with or without an actual avatar attachment). I.e., now it requires the column to actually exist. However, the docs still mention:

```
# NOTE: If you do not specify an [attachment]_content_type field on your
# model, content_type validation will work _ONLY upon assignment_
```

Cheers,
Jimmy
